In [1]:
import numpy as np

# 行列A
A = np.array([
    [0, 1],
    [2, 3],
    [4, 5]
])

# 行列B
B = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7]
])

# 行列の積を計算
C = np.dot(A, B)

# 結果を表示
print("行列A")
print(A)

print("\n行列B")
print(B)

print("\n行列A × B")
print(C)

# 最大値を取得
max_value = np.max(C)

# 最大値を表示
print("\n行列の最大値")
print(max_value)

行列A
[[0 1]
 [2 3]
 [4 5]]

行列B
[[0 1 2 3]
 [4 5 6 7]]

行列A × B
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]

行列の最大値
47
